# Generated by Django 3.1.7 on 2021-03-11 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pattern',
            old_name='artist',
            new_name='added_by',
        ),
    ]
