# Generated by Django 3.1.7 on 2021-03-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0002_auto_20210311_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='category',
            field=models.TextField(default=''),
        ),
    ]
