# Generated by Django 3.1.7 on 2021-03-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0003_pattern_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
